/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArrowDown: typeof import('./src/components/makesvg/ArrowDown.vue')['default']
    ArrowUp: typeof import('./src/components/makesvg/ArrowUp.vue')['default']
    BottomJump: typeof import('./src/components/bottomjump/BottomJump.vue')['default']
    ClaimModal: typeof import('./src/components/modal/ClaimModal.vue')['default']
    Completed: typeof import('./src/components/pages/Completed.vue')['default']
    Confirm: typeof import('./src/components/pages/Confirm.vue')['default']
    ConnectWallet: typeof import('./src/components/topbar/child/ConnectWallet.vue')['default']
    DevelopingPage: typeof import('./src/components/pages/DevelopingPage.vue')['default']
    DropDown: typeof import('./src/components/dropdown/DropDown.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    History: typeof import('./src/components/pages/History.vue')['default']
    HomeBanner: typeof import('./src/components/homeBanner/index.vue')['default']
    InvitePage: typeof import('./src/components/pages/InvitePage.vue')['default']
    LuckyModal: typeof import('./src/components/lottery/LuckyModal.vue')['default']
    MakeSvg: typeof import('./src/components/makesvg/MakeSvg.vue')['default']
    More: typeof import('./src/components/bottomjump/child/More.vue')['default']
    NavBar: typeof import('./src/components/topbar/child/NavBar.vue')['default']
    NCarousel: typeof import('naive-ui')['NCarousel']
    NetworkList: typeof import('./src/components/topbar/child/NetworkList.vue')['default']
    NoData: typeof import('./src/components/pages/NoData.vue')['default']
    NPopover: typeof import('naive-ui')['NPopover']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    PhoneTabbar: typeof import('./src/components/bottomjump/PhoneTabbar.vue')['default']
    PopoverImg: typeof import('./src/components/popover/PopoverImg.vue')['default']
    PopoverText: typeof import('./src/components/popover/PopoverText.vue')['default']
    QRCodeModal: typeof import('./src/components/modal/QRCodeModal.vue')['default']
    Query: typeof import('./src/components/pages/Query.vue')['default']
    QueryLoading: typeof import('./src/components/pages/QueryLoading.vue')['default']
    ReportModal: typeof import('./src/components/modal/ReportModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignInModal: typeof import('./src/components/modal/signInModal.vue')['default']
    SwitchNetwork: typeof import('./src/components/topbar/child/SwitchNetwork.vue')['default']
    Tables: typeof import('./src/components/common/Tables.vue')['default']
    TextLoading: typeof import('./src/components/pages/TextLoading.vue')['default']
    TopBar: typeof import('./src/components/topbar/TopBar.vue')['default']
    VanCollapse: typeof import('vant/es')['Collapse']
    VanCollapseItem: typeof import('vant/es')['CollapseItem']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanEmpty: typeof import('vant/es')['Empty']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPopover: typeof import('vant/es')['Popover']
    VanSwitch: typeof import('vant/es')['Switch']
    WalletList: typeof import('./src/components/topbar/child/WalletList.vue')['default']
    Warn: typeof import('./src/components/makesvg/Warn.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
