<template>
  <div class="commission">
    <div class="title commission">Commission Details</div>
    <div class="content">
      <table class="table">
        <tr class="th">
          <th class="th_item">Address</th>
          <th class="th_item">Active Date</th>
          <th class="th_item">Transactions</th>
          <th class="th_item">
            Commissions

            <PopoverImg
              show-text="The commission generated by your referee's transfer will be updated at 00:10 UTC"
            />
          </th>
        </tr>
        <n-space vertical v-if="isWallet">
          <n-spin :show="loading" stroke="#f5c539">
            <div
              class="scroll"
              v-infinite-scroll="getCommissionData"
              :infinite-scroll-distance="50"
              :infinite-scroll-immediate="false"
            >
              <div v-if="commissionDataLength > 0">
                <tr
                  v-for="(item, index) in commissionData"
                  :class="['td', index % 2 == 0 ? '' : 'bg_white']"
                >
                  <div class="td_address">{{ ellipsis(item.sender) }}</div>
                  <div class="td_active">
                    {{ getHistoryTime(item.active_timestamp) }}
                  </div>
                  <div class="td_bridge">{{ item.count }}</div>
                  <div class="td_commission">
                    <div class="commission">
                      {{ getToFixed(item.commissionsValue, 8) }}
                    </div>
                    <div class="commission_tokenName">
                      {{ item.token }}
                    </div>
                  </div>
                </tr>
              </div>
              <div class="no_data" v-else>
                <van-empty
                  image-size="10rem"
                  description="No Data"
                  class="show"
                />
              </div>
            </div>
          </n-spin>
        </n-space>
        <div class="wallet" @click="wallet" v-else>
          <button>Connect to Get started</button>
        </div>
      </table>
    </div>
  </div>
</template>

<script setup>
import PopoverImg from "@/components/popover/PopoverImg.vue";
import useStore from "@/store";
import {
  getTokenName,
  getChainIcon,
  ellipsis,
  getHistoryTime,
  fromWei,
  getToFixed,
  debounce,
} from "@/common/function";
import { request } from "@/api/request";
import bus from "@/bus";

const { useTokenStore, useUserStore, useWalletStore } = useStore();
const tokenStore = useTokenStore;
const userStore = useUserStore;
const walletStore = useWalletStore;
const showText =
  "The commission generated by your referee's transfer will be updated at 00:10 UTC";

onMounted(async () => {
  await getCommissionCount();
  getCommissionData();
});

const isWallet = computed(() => {
  return walletStore.isWallet;
});

const ths = reactive(["Address", "Active Date", "Transactions", "Commissions"]);

const wallet = () => {
  bus.$emit("onHomeWallet");
};

const loading = ref(false);

const countTotal = ref(0);
const countPageNum = ref(8);
const getCommissionCount = async () => {
  const res = await request({
    url: "reward/commissions-count-v2",
    params: {
      user: userStore.owltoFinanceUserId,
    },
  });
  console.log(res);
  countTotal.value = res.msg.total_count;
  countPageNum.value = res.msg.count_per_page;
};

let commissionData = reactive([]);
let commissionDataLength = ref(0);
let pageNum = ref(1);
const getCommissionData = debounce(async (page = pageNum.value) => {
  const res = await request({
    url: "reward/commissions-list-v2",
    params: {
      user: userStore.owltoFinanceUserId,
      page,
    },
  });

  for (let item of res.msg) {
    item.commissionsValue = await fromWei(item.commission, 18);
    commissionData.push(item);
  }

  console.log("getCommissionData List: ", res.msg);
  commissionDataLength.value = commissionData.length;
  console.log("getCommissionData List-length: ", commissionDataLength.value);
  pageNum.value++;
});

bus.$on("finish", async () => {
  pageNum.value = 1;
  commissionData = [];
  await getCommissionCount();
  getCommissionData();
});
</script>

<style scoped lang="scss">
@media screen and (max-width: 768px) {
  .commission {
    .content {
      width: 580px;
      overflow-x: scroll !important;

      .table {
        .th {
          width: 880px;
        }
      }
    }
  }
}

.commission {
  margin-top: 64px;
  width: 100%;

  .title {
    @include title1;
  }

  .content {
    padding: 24px;
    box-sizing: border-box;
    @include box_shadow;
    background-color: #262626;
    border: none;

    .table {
      width: 100%;
      min-height: 492px;

      .th {
        height: 54px;
        line-height: 54px;
        margin-top: 20px;
        display: flex;
        border-radius: 10px;
        font-weight: 450;
        font-size: 22px;
        background: #181818;

        [data-theme="dark"] & {
          background: #181818;
          color: #fff;
        }

        .th_item {
          flex: 1;

          .iconfont {
            font-size: 22px;
          }
        }
      }

      .scroll {
        max-height: 492px;
        min-height: 492px;
        overflow: auto;

        .td {
          width: 100%;
          font-size: 18px;
          height: 60px;
          display: flex;
          justify-content: center;
          text-align: center;
          align-items: center;
          color: $c7;
          border-radius: 10px;

          [data-theme="dark"] & {
            color: $color7;
          }

          @include trHover;

          .td_address,
          .td_active,
          .td_bridge,
          .td_value,
          .td_commission {
            flex: 1;
          }

          .td_value {
            display: flex;
            align-items: center;
            justify-content: center;

            .value {
              margin: 0 8px;
            }

            .value_icon {
              @include img_size(30px, 30px);
            }
          }

          .td_commission {
            display: flex;
            justify-content: center;
            align-items: center;

            .commission {
              width: auto;
              margin: 0 8px;
            }

            .commission_icon {
              @include img_size(30px, 30px);
            }
          }
        }

        .no_data {
          font-weight: 450;
          font-size: 28px !important;
          height: 400px;
          margin-top: 50px;

          .show {
            padding: 90px 0;
            font-size: 28px !important;
          }
        }

        .bg_white {
          @include trBg;
        }
      }

      .wallet {
        width: 377px;
        height: 44px;
        margin: 175px auto;

        button {
          width: 377px;
          height: 44px;
          background: transparent;
          border: 1px solid $c1;
          border-radius: 12px;
        }
      }
    }
  }
}
</style>
