// bridge url map
export const map = {
  Ethereum: "EthereumMainnet",
  Scroll: "ScrollMainnet",
  Starknet: "StarknetMainnet",
  Base: "BaseMainnet",
  Linea: "LineaMainnet",
  zkSync: "ZksyncMainnet",
  ArbitrumOne: "ArbitrumOneMainnet",
  Optimism: "OptimismMainnet",
  OpBNB: "OpbnbMainnet",
  BNBchain: "BnbMainnet",
  PolygonzkEVM: "PolygonZkMainnet",
  Polygon: "PolygonPoSMainnet",
  Zora: "ZoraMainnet",
  ArbitrumNova: "ArbitrumNovaMainnet",
  Kroma: "KromaMainnet",
  Manta: "MantaMainnet",
  Mantle: "MantleMainnet",
  Goerli: "EthereumGoerli",
  ArbitrumGoerli: "ArbitrumGoerli",
  LineaGoerli: "LineaGoerli",
  ScrollSepolia: "ScrollSepolia",
  ZksyncGoerli: "ZksyncGoerli",
  ZetaTestnet: "ZetaTestnet",
  Sepolia: "EthereumSepolia",
  BnbTestnet: "BnbTestnet",
  OpbnbTestnet: "OpbnbTestnet",
  PGN: "PgnMainnet",
  TaikoJolnir: "TaikoSepolia",
  OkxX1Testnet: "OkxX1Testnet",
  ZKFairTestnet: "ZkfairTestnet",
  ZKFair: "ZkfairMainnet",
  Metis: "MetisMainnet",
  Map: "MAPMainnet",
};

// confirm map
export const map1 = {
  EthereumMainnet: "Ethereum",
  ScrollMainnet: "Scroll",
  StarknetMainnet: "Starknet",
  BaseMainnet: "Base",
  LineaMainnet: "Linea",
  ZksyncMainnet: "zkSync",
  ArbitrumOneMainnet: "Arbitrum One",
  OptimismMainnet: "Optimism",
  OpbnbMainnet: "OpBNB",
  BnbMainnet: "BNBchain",
  PolygonZkMainnet: "Polygon zkEVM",
  PolygonPoSMainnet: "Polygon",
  ZoraMainnet: "Zora",
  ArbitrumNovaMainnet: "Arbitrum Nova",
  KromaMainnet: "Kroma",
  MantaMainnet: "Manta",
  MantleMainnet: "Mantle",
  EthereumGoerli: "Goerli",
  ArbitrumGoerli: "Arbitrum Goerli",
  LineaGoerli: "Linea Goerli",
  ScrollSepolia: "Scroll Sepolia",
  ZksyncGoerli: "zkSync Goerli",
  TaikoSepolia: "Taiko Jolnir",
  ZetaTestnet: "Zeta Testnet",
  EthereumSepolia: "Sepolia",
  BnbTestnet: "Bnb Testnet",
  OpbnbTestnet: "Opbnb Testnet",
  PgnMainnet: "PGN",
  ZkfairTestnet: "ZKFairTestnet",
  ZkfairMainnet: "ZKFair",
  OkxX1Testnet: "OkxX1Testnet",
  MetisMainnet: "Metis",
  MapMainnet: "Map",
};
